[phases.setup]
nixPkgs = ["python311", "libxml2", "libxslt", "zlib", "gcc", "musl-dev"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python kimyo.py"